# Site settingls
title: Martin Lundström
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a site, that has been constructed to solve
  examination task 1 in the course 1DV022 Client-based Web Programming
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://lundst.github.io/ # the base hostname & protocol for your site
twitter_username: none
github_username:  lundst

# Build settings
markdown: kramdown
